"""add external integrations

Revision ID: 9e3a72e00998
Revises: 11bb6303f1bd
Create Date: 2026-08-30 19:08:43.415879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3a72e00998'
down_revision: Union[str, Sequence[str], None] = '11bb6303f1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_external_integration_user_provider')
    )
    op.create_index(op.f('ix_external_integrations_id'), 'external_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_external_integrations_provider'), 'external_integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_external_integrations_user_id'), 'external_integrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_integrations_user_id'), table_name='external_integrations')
    op.drop_index(op.f('ix_external_integrations_provider'), table_name='external_integrations')
    op.drop_index(op.f('ix_external_integrations_id'), table_name='external_integrations')
    op.drop_table('external_integrations')
    # ### end Alembic commands ###
