"""add pkce verifier to oauth states

Revision ID: cb770f43d26f
Revises: a0793303ca64
Create Date: 2026-08-31 12:46:10.060593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb770f43d26f'
down_revision: Union[str, Sequence[str], None] = 'a0793303ca64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_states', sa.Column('code_verifier', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_states', 'code_verifier')
    # ### end Alembic commands ###
